name: asyncy
version: 0.0.11
summary: Asyncy CLI
description: Asyncy CLI
grade: devel
confinement: devmode

apps:
  asyncy:
    command: bin/asyncy

parts:
  asyncy:
    source: https://github.com/asyncy/cli/archive/0.0.11.tar.gz
    plugin: python
    python-version: python3
    python-packages:
    - certifi==2018.8.24
    - chardet==3.0.4
    - click==6.7
    - click-alias==0.1.1a1
    - click-didyoumean==0.0.3
    - click-help-colors==0.4
    - click-spinner==0.1.8
    - emoji==0.5.0
    - idna==2.7
    - lark-parser==0.6.4
    - mixpanel==4.3.2
    - prompt-toolkit==2.0.3
    - Pygments==2.2.0
    - raven==6.9.0
    - requests==2.19.1
    - six==1.11.0
    - storyscript==0.5.1
    - urllib3==1.23
    - wcwidth==0.1.7
